version: "3"

services:
  nginx:
    image: nginxinc/nginx-unprivileged:1.21
    # deploy:
    #   mode: replicated
    #   replicas: 2
    #   placement:
    #     constraints:
    #       - "org.sniper.node.architecture==x86_64"
    ports:
      - "8889:8080"
    environment:
      NGINX_HOST: "lmfaasaas.com"
      NGINX_PORT: $NGINX_PORT
    labels:
      kompose.service.type: LoadBalancer
      # kompose.service.type: NodePort
